### ISSUE TITLE
Use with Nette\Forms standalone

### ISSUE THREAD

**Issue by gebeer** [contributte/reCAPTCHA#11]
Hello, is it possible to use this extension with the standalone Nette\Forms? Without the whole framework.
I installed it via composer and tried adding it like
```php
use Nette\Forms\Form,
Minetro\ReCaptcha\Forms,
Nette\Forms\Controls;
```
But I get an error: Exception: Call to undefined method Nette\Forms\Form::addReCaptcha(). (in /DATA/htdocs/vendor/nette/utils/src/Utils/ObjectMixin.php line 70)

my composer devs:
```
  "require": {
    "php": ">=5.3.8",
    "nette/forms": "^2.4",
    "minetro/recaptcha": "^2.0.0"
  },
```
actual PHP version is 5.7
Without adding recaptcha my form is working fine.

**Comment by f3l1x** [comment]
Hi. Thanks for the question. The answer is YES, but it's little bit complicated.

You have to call `ReCaptchaBinding:bind` manually.

Take a look: https://github.com/minetro/reCAPTCHA/blob/master/src/Forms/ReCaptchaBinding.php#L19-L29

**Comment by f3l1x** [comment]
@gebeer Is everything ok? Can I help you any further?

**Comment by gebeer** [comment]
@f3l1x thank you for looking into this and supplying the link.
 I will continue work on that project next week and will let you know then how it goes.

**Comment by f3l1x** [comment]
I'm closing it now. Feel free to open it again.
