### ISSUE TITLE
Schovávání prvku

### ISSUE THREAD

**Issue by TomasA** [contributte/reCAPTCHA#15]
Nette umožňuje zobrazit/schovat pole a jeho validační pravidla v závislosti na plnění podmínek.

ReCaptcha se sice při splnění podmínky správně nastavuje jako povinné pole, nicméně se javascriptově neschová.
```
$form->addCheckbox("registered","I already have an account.");
$form->addReCaptcha('recaptcha', 'Captcha', false)
	->setOption('id', 'recaptcha')
	->addConditionOn($this["registered"], Form::EQUAL, false)
		->setRequired()
		->toggle('recaptcha');
```
Narazil jsem na stejný problém u jiných prvků, když se přidá validační pravidlo na celý prvek a setRequired() se nastaví až podle podmínky. Například metoda addInteger() automaticky přidává pravidlo FORM::NUMERIC. Aby schovávání fungovalo, musel jsem použít metodu addText() a validační pravidlo přidat až po splnění podmínky.

Dalo by se toto opravit, aby bylo možné prvky s recaptchou schovat?

**Comment by f3l1x** [comment]
Hmm, je to dost zvlastni. 

Vygeneruje se ten toggle spravne? A take, vygeneruje se spravne ID u toho elementu? V jake verzi captchi se tohle deje?

**Comment by TomasA** [comment]
Verze 2.0.1.
Už jsme captchu zkombinoval s jiným rozšířením, takže už to nemůžu potvrdit, ale myslím, že jak ID tak toggle byly vygenerovány správně.

**Comment by f3l1x** [comment]
Diky za odpoved. :-) 

Zkombinoval s jinym rozsirenim znamena prosim co?

**Comment by TomasA** [comment]
Pouzivam ted Nepada/FormRenderer, takze si vsechny prvky generuju sam, nicmene Captcha se porad neschovava.
Prvek captchy se generuje dobre. Obalovy prvek ma id="recaptcha" a je unikatni.
data-nette-rules="[{&quot;op&quot;:&quot;:filled&quot;,&quot;msg&quot;:&quot;Captcha is required.&quot;},{&quot;op&quot;:&quot;:equal&quot;,&quot;rules&quot;:[{&quot;op&quot;:&quot;:filled&quot;,&quot;msg&quot;:&quot;Captcha is required.&quot;}],&quot;control&quot;:&quot;registered&quot;,&quot;toggle&quot;:{&quot;recaptcha&quot;:true},&quot;arg&quot;:false}]"

**Comment by JanGalek** [comment]
vyzkouším na sandboxu, a dám vědět ;), nebo to už není aktuální ? :)

**Comment by f3l1x** [comment]
Rekl bych, ze porad je. Klidne do https://github.com/contributte/playground muzes prihodit invisible recaptcha.

**Comment by JanGalek** [comment]
@TomasA  Tak jo vyzkoušel jsem a jak to máš napsané tak to opravdu nefunguje, uprav to na:

```php
$form->addCheckbox("registered","I already have an account.")
	->addCondition(Form::EQUAL, false)
	>toggle('recaptcha');

$form->addReCaptcha('recaptcha', 'Captcha', false)
	->setOption('id', 'recaptcha')
	->addConditionOn($form["registered"], Form::EQUAL, false)
	->setRequired();
```

Pokud to chápu dobře, tak jak to máš, tak se ten condition přidá na recaptchu, ale né k `registered`

**Comment by JanGalek** [comment]
@f3l1x mám i tento usecase přidat do examplu ?

**Comment by f3l1x** [comment]
Klidne do do playgroundu prihod.

**Comment by TomasA** [comment]
Schovávání teď funguje, pořád ale nefunguje podmíněný setRequired na recaptchu. Formulář pořád tvrdí, že recaptcha je required, i když mám zaškrtnutý registered.
Čekal bych nějakou botu u addConditionOn. U schovávání to jde obejít, u setRequired nevím jak.

**Comment by f3l1x** [comment]
Je to fakt divny.

**Comment by JanGalek** [comment]
@TomasA ještě teda testnu ;)

**Comment by f3l1x** [comment]
@JanGalek Podarilo se nejak otestovat? 
@TomasA Nejake nove info?

**Comment by JanGalek** [comment]
@f3l1x @TomasA na playgroundu funguje dle očekávání ;) - hiddenElementPresenter ;)

**Comment by TomasA** [comment]
Pořád mi to nefunguje, netuším proč. Ale už to používám jinak a tuhle funkci už nepotřebuji.

**Comment by f3l1x** [comment]
Zaviram tedy ;-)
