### ISSUE TITLE
Render error with Tomaj\BootstrapRenderer

### ISSUE THREAD

**Issue by zemnet** [contributte/reCAPTCHA#16]
hi,
I have problem rendering on v. 2.0.0 with nette v2.4,
Form renderer: Tomaj \ BootstrapRenderer.

Div box is rendered with borders in front of reCaptcha box with wrong height ...
"<div class =" g-recaptcha form-control "autocomplete =" off "id =" frm-regForm-recaptcha "

If i remove form-control class, wotk fine, but how can I remove it on single control?

Thank you.

PS: On in 1.6 work fine ....

**Comment by f3l1x** [comment]
Well, it's look a like problem of `BootstrapRenderer`.

Could you please try?

```
{form}
{php $form['recaptcha']->controlPrototype->removeClass('form-control')}
{/form}
```

**Comment by f3l1x** [comment]
And also maybe could you please switch extending of ReCatpchaField from TextInput to BaseControl? It might help.

**Comment by zemnet** [comment]
I don know why, but removeClass not working :( class isn't removed...
but switching to BaseControl works fine...

thank you..

**Comment by f3l1x** [comment]
Could you please send a PR with a patch? :-) I would be great.

**Comment by zemnet** [comment]
sorry, it's beyond my ability :(
