### ISSUE TITLE
Invisible recaptcha + webpack + live form

### ISSUE THREAD

**Issue by martinjinda** [contributte/reCAPTCHA#28]
Hello guys, we want to use invisible reCaptcha, since the regular one is working perfectly. But we got following error from the compiled js script `Nette is not defined`. 

![Screenshot 2019-06-14 at 12 29 38](https://user-images.githubusercontent.com/9948632/59504160-98263e00-8ea2-11e9-8554-530b4e47dc46.png)

If I use the script the included directly in main.js with `window.Nette` or `$.nette` the form is sent but we don't get any response from Nette. We also have the form included in the snippet (#12).

**main.js compiled with webpack**
```php
import 'recaptcha.invisible.js';

require('nette.ajax.js');

window.Nette = require('live-form-validation');
window.Nette.initOnLoad();

$.nette.init();
$.nette.ext('unique');
```

We have (but I tested with Nette 3.0 + reCaptcha 3.2 and it was the same problem).
- Nette 2.4 
- contributte/recaptcha 3.1.0
- PHP 7.2

Has anyone run into the same problem? Thank you

**Comment by f3l1x** [comment]
Hi. Unfortunately I don't know. Maybe others.

**Comment by JanGalek** [comment]
Hi, I'll  look at it this week ;)

**Comment by spulakk** [comment]
Hello, any news on this issue? I'm getting the same error.

Same Nette and ReCaptcha version, PHP 7.1

**Comment by JanGalek** [comment]
I investigated, Have you added https://nette.github.io/resources/js/3/netteForms.min.js too ?

**Comment by JanGalek** [comment]
I investigated, Have you added https://nette.github.io/resources/js/3/netteForms.min.js too ?

ping @martinjinda  @spulakk

**Comment by JanGalek** [comment]
Problem is that it create anonym function so invisibleRecaptcha dont know about this var. I tried add 

```js
window.Nette = require('live-form-validation');
window.Nette.initOnLoad();
```

into invisibleRecaptcha.js and it works.

**Comment by spulakk** [comment]
I tried adding the snippet at the start of invisibleRecaptcha.js and it didn't change anything for me. Also I was fairly time constrained so I went with my own implementation of ReCaptcha already. Thanks for trying though, hopefully it helps @martinjinda at least.

**Comment by JanGalek** [comment]
@spulakk ok :)

Problem solved with configuration webpack

ebpack.config.js:
```js
const path = require('path');
const webpack = require('webpack');

module.exports = {
    entry: './src/index.js',
    output: {
        filename: 'main.js',
        path: path.resolve(__dirname, 'www'),
    },
    plugins: [
        new webpack.ProvidePlugin({
            Nette: 'live-form-validation'
        }),
    ],
};

```
of course remove require of live-form-validation

my index.js
```js
Nette.initOnLoad();
import './invisibleRecaptcha'
```

documentation: https://webpack.js.org/guides/shimming/#shimming-globals

**Comment by martinjinda** [comment]
Thanks @JanGalek. It's great, we start using  `live-form-validation-es6` so you don't have to provide plugin in webpack config. And it works.

**Comment by JanGalek** [comment]
I dont provide plugin, webpack do it itself ;)
