### ISSUE TITLE
minetro/recaptcha:~1.4.0 fpr Nette ~2.2.0

### ISSUE THREAD

**Issue by camohub** [contributte/reCAPTCHA#3]
Zdravím,
akurát hľadám nejakú captchu pre projekt nad Nette ~2.2.0. To podľa dokumentácie znamená nainštalovať minetro/recaptcha:~1.4.0.
To som urobil ale vypadne mi z toho error: 
"ReCaptchaExtension.php – Call to undefined method Nette\PhpGenerator\ClassType::getMethod()"

Podľa dokumentácie by to malo byť $initialize = $class->methods[‚initialize‘]; nie?

Keď som to fixol, tak to začalo fungovať.

**Comment by f3l1x** [comment]
Opravim to.

**Comment by f3l1x** [comment]
Closed via https://github.com/minetro/reCAPTCHA/commit/cf1496d2ca35b6178ae7c2b600a7476645ad6515

**Comment by f3l1x** [comment]
Is it oukey @camohub?

**Comment by camohub** [comment]
Yes, thanks for quick riekšn.

**Comment by camohub** [comment]
Now I am going to update the project to Nette 2.4 so stay tuned :)

**Comment by camohub** [comment]
Tak som tu znova, kôli tomu Nette 2.4. Nemohol by si otagovať verziu 1.7? Mám v 
composer.json   "minimum-stability": "stable", "prefer-stable": true a 1.7.x-dev mu nestačí.

**Comment by f3l1x** [comment]
Zkus 1.6.0. 1.7 je jenom budouci alias pro nette 2.4.

**Comment by camohub** [comment]
Ok vyskúšam. Díky.
