### ISSUE TITLE
contributte reCAPTCHA nelze nainstalovat

### ISSUE THREAD

**Issue by maggi1** [contributte/reCAPTCHA#33]
Ahoj, stáhl jsem si přes composer poslední verzi nette (3,0). Při instalaci contributte recaptcha (composer) mi to hází chybu:

C:\xampp\htdocs\web-project>composer require contributte/recaptcha
Using version ^3.2 for contributte/recaptcha
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for contributte/recaptcha ^3.2 -> satisfiable by contributte/recaptcha[3.2.0].
    - Conclusion: remove nette/utils v3.1.0
    - Conclusion: don't install nette/utils v3.1.0
    - contributte/recaptcha 3.2.0 requires nette/utils ~3.0.0 -> satisfiable by nette/utils[v3.0.0, v3.0.1, v3.0.2, v3.0.3].
    - Can only install one of: nette/utils[v3.0.0, v3.1.0].
    - Can only install one of: nette/utils[v3.0.1, v3.1.0].
    - Can only install one of: nette/utils[v3.0.2, v3.1.0].
    - Can only install one of: nette/utils[v3.0.3, v3.1.0].
    - Installation request for nette/utils (locked at v3.1.0, required as ^3.0) -> satisfiable by nette/utils[v3.1.0].

Installation failed, reverting ./composer.json to its original content.

Co s tím?

**Comment by jiripudil** [comment]
[Tento commit](https://github.com/contributte/reCAPTCHA/commit/b8200ee8077e6849fa9331a9733419f4eed4920c) to spravuje, jen ještě není releasnutý. Než se tak stane, můžeš vyžadovat `^3.3@dev`

**Comment by f3l1x** [comment]
Vydal jsem novou verzi, zkus to prosim.

https://github.com/contributte/reCAPTCHA/releases/tag/v3.3.0

**Comment by maggi1** [comment]
jak bych to udělal přes composer?

**Comment by f3l1x** [comment]
Jak pise @jiripudil.

```
{
  "require": {
    "contributte/reCAPTCHA": "^3.3@dev"
  }
}
```

Kazdopadne, tedka uz to neni potreba, protoze jsem vydal novou verzi.

**Comment by maggi1** [comment]
Nainstalováno přes composer bez problémů. Díky
