### ISSUE TITLE
Problém s validací

### ISSUE THREAD

**Issue by jAKErCZ** [contributte/reCAPTCHA#35]
Zdravím 
Dle dokumentace mám nasazenou reCEPTCHA
`$form->addReCaptcha('recaptcha', $label = 'Captcha', $required = TRUE, $message = 'Nejsi robot?');`
a latte
`  <div class="form-group">
            <div n:name="recaptcha"></div>
        </div>`
Ale problém je v tom že i když nezakliknu reCAPTCHA tak se mi odešle foirmulář a nevyskočí mi hláška **Nejsi robot?**

Proč?

**Comment by mabar** [comment]
Skript máš přilinkovaný? V konzoli žádná chyba?

**Comment by jAKErCZ** [comment]
Ano mám, a v konzoli nic..

**Comment by WeaponMan** [comment]
To same se mi stalo na produkcnim serveru...
Prisel jsem na to ze se tam vola `file_get_contents` coz kdyz je na serveru  `allow_url_fopen Off` tak validace nikdy neprojde..
Takze jedine co pomuze zapnout `allow_url_fopen` nebo upravit zdrojak, aby pouzil `ext-curl` misto `file_get_contents`.

**Comment by f3l1x** [comment]
Ano, `allow_url_fopen` musi byt povolene. Nenapadlo me, ze by to nekdo zakazoval.

**Comment by WeaponMan** [comment]
Ja bych rekl ze na sdilenem hostingu `allow_url_fopen On` je celkem nebezpecna vec a mnoho hostingu ji ma vypnutou.

**Comment by WeaponMan** [comment]
A jeste jedna vec pokud mas nastavene `$required = TRUE` a nezakliknes recaptchu tak se zobrazuje hlaska `This field is required!` a pokud tam chces jinou musis hlasku nastavit skrz `$form['recaptcha']->setRequired('Nejsi robot?');`.

**Comment by jAKErCZ** [comment]
Vyzkoušel jsem rady a na localhostu mi to stále nevaliduje i když mám `allow_url_fopen` na On. Čím to tedy může ještě být?
