### ISSUE TITLE
No way to set score threshold for invisible reCAPTCHA

### ISSUE THREAD

**Issue by fmasa** [contributte/reCAPTCHA#40]
Hi,
first of all, thank you for this package!

I was just wondering whether the score returned for invisible Captcha is checked in any way (I haven't found any in the code).
If I understand correctly `success` field means merely that the ReCaptcha challenge site matches the one associated with
the secret key. (https://developers.google.com/recaptcha/docs/v3#site_verify_response)

To verify that request didn't come from a bot, the returned score must be compared to an application-specific threshold, right?

**Comment by fmasa** [comment]
Oh, or maybe I am just confused from https://github.com/contributte/reCAPTCHA/pull/21. This is not really a ReCAPTCHA v3 as stated in PR title, but "just" invisible version of v2?

**Comment by fmasa** [comment]
> Oh, or maybe I am just confused from #21.

Yes, of course I am. Would you consider maybe mentioning that this is Invisible ReCAPTCHA v2 (or should I do so?)

**Comment by f3l1x** [comment]
Hi @fmasa, sorry for confusing, it's long time I used recaptcha so I don't watch versions. Please, could you please prepare PR with clarification and re-title? :-)

**Comment by PavelWeirich** [comment]
it's solved in version 4.0.1 https://github.com/contributte/reCAPTCHA/releases/tag/v4.0.1
