### ISSUE TITLE
PHP 8 compatibility

### ISSUE THREAD

**Issue by TomasA** [contributte/reCAPTCHA#41]
Hello,
I have a problem with PHP 8.0 and composer update. After update to PHP 8.0 the composer won't resolve the reCAPTCHA because:

`- contributte/recaptcha[v3.3.0, ..., v3.3.1] require php ^7.2 -> your php version (8.0.0) does not satisfy that requirement.`

I guess that the package is already PHP 8.0 compatible but the `php ^7.2` requirement prevents the composer from its usage. Would it be possible to make a quick fix and release a version which will state a compatibility with PHP 8.0?

Thanks.

**Comment by f3l1x** [comment]
Resolved.
