### ISSUE TITLE
Nette Configurator issue

### ISSUE THREAD

**Issue by camohub** [contributte/reCAPTCHA#5]
Hi,
I have installed new release 1.6.1 (like ~1.6.0 in composer.json), and it throws me an error:
Syntax error unexpected ":" in ...

    File: ...\cache\Nette.Configurator\Container_5c35485316.php:7855

    7845:            $this->getService('tracy.bar')->addPanel(new Nette\Bridges\DITracy\ContainerPanel($this));
    7846:            $this->getService(191);
    7847:            header('X-Frame-Options: SAMEORIGIN');
    7848:            header('X-Powered-By: Nette Framework');
    7849:            header('Content-Type: text/html; charset=utf-8');
    7850:            $this->getService('session.session')->start();
    7851:            Tracy\Debugger::setLogger($this->getService('tracy.logger'));
    7852:            if ($tmp = $this->getByType("Nette\Http\Session", FALSE)) { $tmp->start(); Tracy\Debugger::dispatch(); };
    7853:            if (!class_exists('WebLoader\LoaderFactory', FALSE)) class_alias('WebLoader\Nette\LoaderFactory', 'WebLoader\LoaderFactory');
    7854:            Minetro\Forms\reCAPTCHA\ReCaptchaBinding::bind('6LcYBgsUAAAAADhF7EVIrbDLCzjzsSZ6geiZhQoh');
    7855:            :factory('6LcYBgsUAAAAADhF7EVIrbDLCzjzsSZ6geiZhQoh');
    7856:        }

Version 1.6.0 is ok.

**Comment by f3l1x** [comment]
Thank you for feedback. It's fixed in ~1.6.2.
