### ISSUE TITLE
Composer nechce nainstalovat contributte/recaptcha

### ISSUE THREAD

**Issue by tommy8699** [contributte/reCAPTCHA#51]
Zdravim, 
Mam problem s instalaciou contributte recaptcha po vlozeni composer require contributte/recaptcha mi zobrazi ze instalacia prebieha a nasledne vypise instalation failed composer.json vracia do povodneho stavu:

`
composer require  contributte/recaptcha:3.4.0
./composer.json has been updated
Running composer update contributte/recaptcha
Loading composer repositories with package information
Updating dependencies
Lock file operations: 3 installs, 0 updates, 0 removals
  - Locking contributte/di (v0.5.1)
  - Locking contributte/recaptcha (v3.4.0)
  - Locking nette/forms (v3.0.7)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals
  - Installing nette/forms (v3.0.7): Extracting archive
  - Installing contributte/di (v0.5.1): Extracting archive
  - Installing contributte/recaptcha (v3.4.0): Extracting archive
1 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating autoload files

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

  [ErrorException]
  file_put_contents(C:\Users\OVDPOSRTrebišov\Desktop\snapbackuper-web\vendor\bin/tester): failed to open stream: No such file or directory

require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-scripts] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>]...
`

skusal som aj vyssiu verziu dev a tak isto rovnako. S contributte translation som nemal problem.
Dakujem za pomoc.

**Comment by petrparolek** [comment]
toto nemá souvislost s recaptchou. Smaž celou složku vendor a spust composer install a mělo by vše stáhnout ok.

**Comment by f3l1x** [comment]
ping @tommy8699
