### ISSUE TITLE
Nette\Forms\Container::getValues() invoked but the form is not valid

### ISSUE THREAD

**Issue by otoman** [contributte/reCAPTCHA#53]
Nette Forms 3.1.3 with onValidate callback ($form->getValues()) ends with error. 
![tracy](https://user-images.githubusercontent.com/297570/110209751-6a5f0500-7e8e-11eb-998f-29961b30235d.png)

Nette Forms 3.0.7 works fine...

**Comment by f3l1x** [comment]
There is something new in nette/forms 3.1. Just use nette/form < 3.1 for now.

**Comment by otoman** [comment]
Ok :)
