### ISSUE TITLE
Support reCAPTCHA v3 Actions 

### ISSUE THREAD

**Issue by o5** [contributte/reCAPTCHA#56]
I would like to use it with [actions](https://developers.google.com/recaptcha/docs/v3#actions) but it looks like this feature is not supported, right? 

```js
<script>
  function onClick(e) {
    e.preventDefault();
    grecaptcha.ready(function() {
      grecaptcha.execute('reCAPTCHA_site_key', {action: 'SPECIFIC-ACTION'}).then(function(token) {
          // Add your logic to submit to your backend server here.
      });
    });
  }
</script>
```

**Comment by f3l1x** [comment]
Hi @o5. I must say I don't know what reCAPTCHA v3 actions are. :-) So it is probably unsupported at this moment. Feel free to implement it.

**Comment by o5** [comment]
I had to create an own simplified version of this control, without dependency to `contributte/di`. Unfortunately I cannot open-source them.
