### ISSUE TITLE
Undefined array key "score"

### ISSUE THREAD

**Issue by bohacf** [contributte/reCAPTCHA#65]
After updating to version 4.0.1, PHP throws this warning:

PHP Warning: Undefined array key "score" in .../vendor/contributte/recaptcha/src/ReCaptchaProvider.php:66  

`
return $answer['success'] === true && $answer['score'] >= $this->minimalScore ? new ReCaptchaResponse(true) : new ReCaptchaResponse(false, $answer['error-codes'] ?? null);
`

**Comment by bohacf** [comment]
I'm using the non-score version of reCaptcha 2. Here is a possible fix:

`
return $answer['success'] === true && ($this->minimalScore <= 0 || !isset($answer['score']) || $answer['score'] >= $this->minimalScore) ? new ReCaptchaResponse(true) : new ReCaptchaResponse(false, $answer['error-codes'] ?? null);
`

**Comment by f3l1x** [comment]
Let me know @bohacf. It's in master.

**Comment by bohacf** [comment]
ReCaptchaProvider.php from master works fine. Thanks for the fix @f3l1x  :)
