### ISSUE TITLE
Missing setRequired(TRUE | FALSE) on field 'recaptcha' in form 'xxxForm'

### ISSUE THREAD

**Issue by sallyx** [contributte/reCAPTCHA#9]
`$form->addRecaptcha()` shows reCaptcha, but not validate it.
`$form->addRecaptcha()->setMessage('Are you bot?');` triggers warning "Missing setRequired(TRUE | FALSE) on field 'recaptcha' in form 'xxxForm'"
`$form->addRecaptcha()->setRequired(FALSE)->setMessage('Are you bot?');` doesnt validate.
`$form->addRecaptcha()->setRequired(TRUE)->setMessage('Are you bot?');` doesnt show 'Are you bot?' but 'This field is required' if form is submited without checking reCaptcha.

**Comment by f3l1x** [comment]
Thank you for bug report.

What do you suggest?

**Comment by f3l1x** [comment]
What version of nette do you use?

**Comment by sallyx** [comment]
Nette 2.4

**Comment by f3l1x** [comment]
Could you try change this rule?

https://github.com/minetro/reCAPTCHA/blob/master/src/Forms/ReCaptchaField.php#L48

Maybe try combination with `setOmitted()`.
